version: '3.3'
services:
  database-finance:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'finance'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db-finance:/var/lib/mysql

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    networks:
      - dev-network

volumes:
  db-finance:

networks:
  dev-network:
    driver: bridge